name: kurdi_poli_yak
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git
  flutter:
    sdk: flutter
  flutter_rating_bar: ^3.0.1+1
  cloud_firestore: ^0.13.2+1
  cupertino_icons: ^0.1.2
  audioplayers: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/