name: kurdi_poli_yak
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git
  flutter:
    sdk: flutter
  flutter_rating_bar: ^3.0.1+1
  cloud_firestore: ^0.13.2+1
  cupertino_icons: ^0.1.2
  audioplayers: ^0.12.0
  folding_cell: "^0.1.2"
  clay_containers: ^0.2.2
  rounded_loading_button: ^1.0.0
  slide_container: ^1.1.3
  flutter_animator: ^2.0.6
  flare_flutter: ^1.5.0
  positioned_tap_detector: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.21.0
  painter2: any
  flutter_colorpicker: ^0.2.1
flutter:
  uses-material-design: true
  assets:
    - assets/
